bw_user_bundle_role:
    resource: "@BWUserBundle/Resources/config/routing/role.yml"
    prefix:   /role

bw_user_bundle_role_admin:
    resource: "@BWUserBundle/Resources/config/routing/role_admin.yml"
    prefix:   /_admin/role

bw_user_bundle_user:
    resource: "@BWUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

bw_user_bundle_user_admin:
    resource: "@BWUserBundle/Resources/config/routing/user_admin.yml"
    prefix:   /_admin/user
